version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    tty: true
    ports:
      - 80:80
    volumes:
      - ./apps/wallet/:/var/www/wallet
      - ./apps/discount/:/var/www/discount
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/apps/:/etc/nginx/conf.d/
    restart: always

  wallet:
    build:
      context: apps/wallet
      dockerfile: Dockerfile
    container_name: wallet_microservice
    environment:
      SERVICE_NAME: wallet
      SERVICE_TAGS: dev
    working_dir: /var/www/wallet
    volumes:
      - ./apps/wallet/:/var/www/wallet
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - "rabbitmq"
    tty: true
    restart: unless-stopped

  discount:
    build:
      context: apps/discount
      dockerfile: Dockerfile
    container_name: discount_microservice
    environment:
      SERVICE_NAME: discount
      SERVICE_TAGS: dev
    working_dir: /var/www/discount
    volumes:
      - ./apps/discount/:/var/www/discount
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - "rabbitmq"
    tty: true
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    restart: always
    container_name: rabbitmq
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    ports:
      - 15672:15672

  gateway-api:
    container_name: gateway-api
    build:
      context: apps/gateway-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
